### ISSUE TITLE
Trips iCal/rss feed

### ISSUE THREAD

**Issue by toolmantim** [toolmantim/vcc-website#2]

**Comment by toolmantim** [comment]
A sort-of-not-really working version was added in 98f92526115eb6691f168cbfea883d9eae563834 via `/feed?feed=events-ical`

**Comment by ajfclark** [comment]
When we go llive, there's a hard coded hostname for the selfref link in the RSS script that needs to be updated. I could probably get the host header from the GET request somewhere and use that if I thought about it.

**Comment by toolmantim** [comment]
Cool. And perhaps this would be a good time to drop the "www" and just go "vicclimb.org.au"… w/ a redirect rule to send any www requests to the www-less version.

**Comment by ajfclark** [comment]
Agreed.
