### ISSUE TITLE
Add image field to events

### ISSUE THREAD

**Issue by ajfclark** [toolmantim/vcc-website#20]
Michael has requested that he be able to add an image to events. I'm not sure how this could be worked in, but it'd be best if it wasn't in the description as HTML.

**Comment by toolmantim** [comment]
Cool, we can add more custom fields using the custom fields editor in the WP admin easily enough! Then we need to update the template to display it.

Can Michael send through the image(s) and which event?

**Comment by toolmantim** [comment]
@ajfclark any word?

**Comment by ajfclark** [comment]
@toolmantim Michael didn't have any specifics really, it was just "It'd been cool to add a rack photo to the l2l trips".

**Comment by toolmantim** [comment]
@ajfclark I think a sensible first step is to always just add it to the body, and then I can fix it up and make it better (that might just be styles, or could be a custom field). Just get him to add the rack photo and I'll fix up the rest.

**Comment by ajfclark** [comment]
I'm just worried about it popping through into the RSS. That'd make it pop
up on the front page of chockstone which wouldn't be a good thing.

Actually, I think I might strip tags. I should check.

**Comment by ajfclark** [comment]
Looks like I do strip tags.

OK. I'll teach Michael to add images in the HTML and then we can refine it.

**Comment by toolmantim** [comment]
Ok cool! Then he can have fun making the event pages as enticing as possible, I can fix up the styles, and he want to standardize the layout we can switch to custom fields and what not

**Comment by toolmantim** [comment]
*if we want to standardise
