### ISSUE TITLE
header.php

### ISSUE THREAD

**Issue by ajfclark** [toolmantim/vcc-website#21]
Does this stuff need to still be in the header:

```
  <!-- live reload in local dev only -->
  <script>document.write('<script src="http://localhost:35729/livereload.js?snipver=1"></' + 'script>')</script>
```

**Comment by toolmantim** [comment]
If we want the styles to livereload when I'm editing stylesheets yeah. But it should only affect dev/localhost because of the if statement. What's the prob? I could also just enable it with an environment variable instead of the host name check if that fixes some issue you're having?

**Comment by ajfclark** [comment]
I just noticed chrome saying there was an error in the page, that's all.

**Comment by toolmantim** [comment]
Locally?

**Comment by toolmantim** [comment]
Ah, I see it happens on prod too. That's a bug!
